import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import categories from "../data/categories";
import CategorySelector from "../components/CategorySelector";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Knowit <span className={styles.subTitle}>TechRadar 2021</span>
      </h1>

      <p className={styles.description}>
        Velkommen til Knowit Techradar. Punktene på radaren er resultatet av
        interne workshops og flere runder med teamene våre. Dette representerer
        vår kompetanse, kunnskap og det vi tror er essensielt i nær fremtid.
      </p>

      <div className={styles.categoryWrapper}>
        <CategorySelector categories={Object.values(categories)} />
      </div>
    </div>
  );
};

export default Home;
