name: 'Deploy to AWS PROD env'

on:
  workflow_dispatch:

jobs:
  install-and-deploy-prod:
    name: Install and deploy prod
    uses: ./.github/workflows/reusable-install-and-deploy.yml
    with:
      domain: teknologiradar-objectnet.knowit.no
    secrets:
      cdk_default_account: ${{ secrets.PROD_CDK_DEFAULT_ACCOUNT }}
      aws_default_region: ${{ secrets.CDK_DEFAULT_REGION }}
      aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
