name: Deploy website

on:
  push:
    branches: [685-github-actions-deploy] # TODO: change to main
  pull_request:
    branches: [685-github-actions-deploy] # TODO: change to main

defaults:
  run:
    working-directory: ./

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Hello world
        run: echo Hello world

      - name: Ls
        run: ls
