name: 'Deploy website to dev'
description: 'Installs and deploys website to AWS dev environment'

on:
  push:
    branches: [688-github-actions-deploy-prod] # TODO: change to main

jobs:
  install-and-deploy-dev:
    uses: ./.github/workflows/install-and-deploy.yml
    secrets:
      cdk_default_account: ${{ secrets.DEV_CDK_DEFAULT_ACCOUNT }}
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.DEV_AWS_SESSION_TOKEN }}
