name: Deploy website

on:
  push:
    branches: [685-github-actions-deploy] # TODO: change to main
  pull_request:
    branches: [685-github-actions-deploy] # TODO: change to main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Python and pip version
        run: python3 --version && python3 -m pip --version

      - name: Install pandas
        run: python3 -m pip install pandas

      - name: Install and deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: eu-central-1
        run: echo $AWS_ACCESS_KEY_ID