name: 'Deploy website to prod'
description: 'Installs and deploys website to AWS S3 production environment'

on:
  push:
    branches: [688-github-actions-deploy-prod] # TODO: change to main

jobs:
  install-and-deploy-prod:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install-and-deploy
        secrets:
          cdk_default_account: ${{ secrets.DEV_CDK_DEFAULT_ACCOUNT }}
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.DEV_AWS_SESSION_TOKEN }}
