name: 'REUSABLE WORKFLOW: Deploy website'
#description: 'Deploy website to AWS dev or prod environment based on secrets input'

on:
  workflow_call:
    secrets:
      cdk_default_account:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_session_token:
        required: true

jobs:
  install-and-deploy:
    name: Reusable deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Python and pip version
        run: python3 --version && python3 -m pip --version

      - name: Install pandas
        run: python3 -m pip install pandas

      - name: Install and deploy
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.cdk_default_account }} #${{ secrets.DEV_CDK_DEFAULT_ACCOUNT }}
          AWS_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }} #${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }} #${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.aws_session_token }} #${{ secrets.DEV_AWS_SESSION_TOKEN }}
        run: ./install-and-deploy.sh

# outputs?